config/routes.rb
Santeh::Application.routes.draw do
  resources :proposals

  resources :reviews

  resources :services

  resources :servces

  resources :contents
  
  root :to => 'pages#home'
  
  match '/home', :to => 'pages#home'

end

app/models/content.rb
class Content < ActiveRecord::Base
  attr_accessible :alias, :content
  
  validates :alias, :content, presence: true
  validates :alias, uniqueness: true
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_filter :require_login
  
  def index
    @contents = Content.all
  end

  def show
    @content = Content.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @content }
    end
  end

  # GET /contents/new
  # GET /contents/new.json
  def new
    @content = Content.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @content }
    end
  end

  # GET /contents/1/edit
  def edit
    @content = Content.find(params[:id])
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(params[:content])

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render json: @content, status: :created, location: @content }
      else
        format.html { render action: "new" }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contents/1
  # PUT /contents/1.json
  def update
    @content = Content.find(params[:id])

    respond_to do |format|
      if @content.update_attributes(params[:content])
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content = Content.find(params[:id])
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contents_url }
      format.json { head :no_content }
    end
  end
  

end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_for(@content) do |f| %>
  
  <%= f.label :alias %>
  <%= f.text_field :alias %>
  
  <%= f.label :content %>
  <%= f.text_area :content %>
  
  <%= f.submit "Create content", class: "btn btn-large btn-primary" %>

<% end %>

app/views/contents/edit.html.erb
<% provide(:title, "Edit content") %>
<h1>Editing content</h1>

<div class="row">
  <div class="span6 offset3">
    <%= render 'form' %>
    
    <%= link_to 'Show', @content %> |
    <%= link_to 'Back', contents_path %>
  </div>
</div>

app/views/contents/index.html.erb
<h1>Listing contents</h1>

<table>
  <tr>
    <th>Alias</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contents.each do |content| %>
  <tr>
    <td><%= content.alias %></td>
    <td><%= content.content %></td>
    <% if session[:admin] %>
      <td><%= link_to 'Show', content %></td>
      <td><%= link_to 'Edit', edit_content_path(content) %></td>
      <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<% if session[:admin] %>
  <%= link_to 'New Content', new_content_path %>
<% end %>

app/views/contents/new.html.erb
<% provide(:title, "New content") %>
<h1>New content</h1>

<div class="row">
  <div class="span6 offset3">
    <%= render 'form' %>
    
    <%= link_to 'Back', contents_path %>
  </div>
</div>

app/views/contents/show.html.erb
<% provide(:title, @content.alias) %>
<div class="row">
    <b>Alias:</b>
    <%= @content.alias %>
  </p>
  
  <p>
    <b>Content:</b>
    <%= @content.content %>
  </p>
  
  
  <%= link_to 'Edit', edit_content_path(@content) %> |
  <%= link_to 'Back', contents_path %>
</div>