config/routes.rb
Santeh::Application.routes.draw do
  resources :proposals

  resources :reviews

  resources :services

  resources :servces

  resources :contents
  
  root :to => 'pages#home'
  
  match '/home', :to => 'pages#home'

end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  attr_accessible :address, :description, :name, :phone
  
  validates :address, :description, :name, :phone, presence: true
  
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_filter :require_login, :only => [:update, :delete, :edit, :index, :show]
  
  # GET /proposals
  # GET /proposals.json
  def index
    @proposals = Proposal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proposals }
    end
  end

  # GET /proposals/1
  # GET /proposals/1.json
  def show
    @proposal = Proposal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proposal }
    end
  end

  # GET /proposals/new
  # GET /proposals/new.json
  def new
    @proposal = Proposal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proposal }
    end
  end

  # GET /proposals/1/edit
  def edit
    @proposal = Proposal.find(params[:id])
  end

  # POST /proposals
  # POST /proposals.json
  def create
    @proposal = Proposal.new(params[:proposal])

    respond_to do |format|
      if @proposal.save
        ProposalNotifier.received(@proposal).deliver
        format.html { redirect_to root_path, notice: 'Proposal was successfully created.' }
        format.json { render json: @proposal, status: :created, location: @proposal }
      else
        format.html { render action: "new" }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proposals/1
  # PUT /proposals/1.json
  def update
    @proposal = Proposal.find(params[:id])

    respond_to do |format|
      if @proposal.update_attributes(params[:proposal])
        format.html { redirect_to @proposal, notice: 'Proposal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1
  # DELETE /proposals/1.json
  def destroy
    @proposal = Proposal.find(params[:id])
    @proposal.destroy

    respond_to do |format|
      format.html { redirect_to proposals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/_form.html.erb
<%= form_for(@proposal) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :address %>
  <%= f.text_area :address, rows: 6 %>
 
  <%= f.label :description %>
  <%= f.text_area :description, rows: 6 %>
  
  <%= f.submit "Create proposal", class: "btn btn-large btn-primary" %>

<% end %>

app/views/proposals/edit.html.erb
<h1>Editing proposal</h1>

<%= render 'form' %>

<%= link_to 'Show', @proposal %> |
<%= link_to 'Back', proposals_path %>

app/views/proposals/index.html.erb
<h1>Listing proposals</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th>Address</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @proposals.each do |proposal| %>
  <tr>
    <td><%= proposal.name %></td>
    <td><%= proposal.phone %></td>
    <td><%= proposal.address %></td>
    <td><%= proposal.description %></td>
    <% if session[:admin] %> 
      <td><%= link_to 'Show', proposal %></td>
      <td><%= link_to 'Edit', edit_proposal_path(proposal) %></td>
      <td><%= link_to 'Destroy', proposal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<% if session[:admin] %>
  <%= link_to 'New Proposal', new_proposal_path %>
<% end %>

app/views/proposals/new.html.erb
<% provide(:title, 'New proposal') %>

<h1>New proposal</h1>
  
  
<div class="row">
  <div class="span6 offset3">
    <%= render 'form' %> 
    
    <%= link_to 'Back', proposals_path %>
  </div>
</div>

app/views/proposals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @proposal.name %>
</p>

<p>
  <b>Phone:</b>
  <%= @proposal.phone %>
</p>

<p>
  <b>Address:</b>
  <%= @proposal.address %>
</p>

<p>
  <b>Description:</b>
  <%= @proposal.description %>
</p>


<%= link_to 'Edit', edit_proposal_path(@proposal) %> |
<%= link_to 'Back', proposals_path %>