config/routes.rb
Santeh::Application.routes.draw do
  resources :proposals

  resources :reviews

  resources :services

  resources :servces

  resources :contents
  
  root :to => 'pages#home'
  
  match '/home', :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <footer class="footer">
      <small>
        <a href="http://ferret.pp.ua/">Santeh</a>
        by Ferret
      </small>
      <nav>
        <ul>
          <li><%= link_to "О Нас" %></li>
          <li><%= link_to "Контакты" %></li>
          <li><a href="http://news.railstutorial.org/">Новости</a></li>
        </ul>
      </nav>
    </footer>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Сантехник", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to 'Домой', root_path %></li>
          <li><%= link_to 'Услуги', services_path%></li>
          <li><%= link_to 'Заказ', new_proposal_path %></li>
          <li><%= link_to 'Отзыв', new_review_path %></li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Admin <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Content', contents_path %></li>
            </ul>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_stylesheets.html.erb
   <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <!--[endif]-->
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div id="wrap">
    <%= render 'layouts/header' %>
    
    
      <div class="container">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
        <% end %>
        <%= yield %>
        <%= render 'shared/ten_reviews' %>
        <%= debug(params) if Rails.env.development? %>
        <%= render 'layouts/footer' %>
      </div>
    </div>
    
  </body>
</html>